language: java
sudo: true
os: linux
dist: bionic
services:
  - postgresql
jdk:
  - openjdk11
before_script:
  - sudo apt update
  - sudo apt -y install libargon2-0
  - psql -c "CREATE ROLE test NOSUPERUSER NOCREATEROLE NOCREATEDB LOGIN INHERIT NOREPLICATION ENCRYPTED PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test OWNER test;" -U postgres
after_script:
  - bash <(curl -s https://codecov.io/bash)
