language: java
sudo: false
os: linux

services:
  - postgresql

jdk:
  - openjdk8

env:
  - CODECOV_TOKEN="e82eec56-0789-43ab-ab40-63284a99d9cd"

before_script:
  - psql -c "CREATE ROLE test NOSUPERUSER NOCREATEROLE NOCREATEDB LOGIN INHERIT NOREPLICATION ENCRYPTED PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test OWNER test;" -U postgres

after_script:
  - bash <(curl -s https://codecov.io/bash)
