language: java
sudo: false
os: linux

services:
  - postgresql

jdk:
  - openjdk8

before_script:
  - psql -c "CREATE ROLE test NOSUPERUSER NOCREATEROLE NOCREATEDB LOGIN INHERIT NOREPLICATION ENCRYPTED PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test OWNER test;" -U postgres

after_script:
  - bash <(curl -s https://codecov.io/bash)
