language: java
sudo: true
os: linux
dist: bionic
services:
  - postgresql
jdk:
  - openjdk11
before_script:
  - sudo apt update
  - sudo apt -y install libargon2-0
  - psql -c "CREATE USER test LOGIN ENCRYPTED PASSWORD 'test';" -U postgres
  - psql -c "CREATE DATABASE test OWNER test;" -U postgres
