name: Check
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  check:
    name: "Run tests and CodeCoverage"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenJDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build
        run: ./gradlew war
      - name: Run tests
        run: ./gradlew check
      - name: Send reports to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
