name: Check
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
jobs:
  check:
    name: Build, Tests, and send results to CodeCoverage and SonarQube
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      activemq:
          image: rmohr/activemq
          ports:
            - 61616:61616
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenJDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build
        run: ./gradlew war
      - name: Run tests
        run: ./gradlew check
      - name: Run Sonarqube
        run: ./gradlew sonarqube
      - name: Send reports to CodeCov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload WAR artifact
          uses: actions/upload-artifact@v2
          with:
            name: lanparty-manager.war
            path: build/libs/lanparty-manager.war